### ISSUE TITLE
Traceback error after authenticate

### ISSUE THREAD

**Issue by anandakelvin** [merkremont/LineVodka#19]
Hi folks i get this error when running it on termux https://pasteboard.co/GYseZ2C.jpg
and when running it from my vps https://pasteboard.co/GYj4Zhf.png

any response would be very appreciated!

**Comment by anandakelvin** [comment]
##the termux one is LineVodka and the vps one is LineChivas

**Comment by doodspav** [comment]
LINE is updating their api, and theyve changed login. So current login by qr will yield an authtoken that's not recognised as being generated using the new method and will be rejected (or something like that). Authtokens generated before the update will work as normal until 2018 (or i think 30days).

**Comment by Dewamade** [comment]
Yeah i think they change how to request the qr login, its not that simple by change only the headers request, sniffing the line app i found something really different, i think it need more time to RE the api

**Comment by cosadiz69** [comment]
this thing can be overcome

**Comment by fpitlok** [comment]
I know the reason is because LINE brings the certificate encryption.

It's easy to fix
you can find a CHOME user-agent to use, because CHOME has a valid certificate.

But It does not use the correct solution, because the real problem is "SSL" encryption.

I can only say this.
good luck 😊

**Comment by doodspav** [comment]
apparently login via email is fine so gonna implement that when i have the time - also @fpitlok if you're using chrome as a user-agent, how are you getting the authtoken? cuz atm for qr login im sniffing line chrome app, and that authtoken expires after one day

**Comment by anandakelvin** [comment]
@doodspav cool!!! please notify us ASAP!!

**Comment by fpitlok** [comment]
yes.. because login by email&mobile number have certificate 

# but How to find Token is another way. And it's the right way. Please see here.

- [ ] https://developers.line.me/en/docs/line-login/web/integrate-line-login/

**Comment by semarainc** [comment]
@fpitlok i think that article is for line@, and it wont work on regular line account.

Correct me if im wrong
