### ISSUE TITLE
Beberapa issue

### ISSUE THREAD

**Issue by winbotscript** [merkremont/LineVodka#3]
Terima kasih sebelumnya sudah kasih script ini dan sudah bisa login akan tetapi saya ingin bertanya beberapa hal 

1. Saya pakai centos 6.9 Final utk install pyton 2.7 nya dan ketika saya close Putty ssh nya kenapa tidak berfungsi lagi yah semua command nya ???
2. Utk command Kick, NK dan gname kenapa tidak berfungsi yah sob ???

Tolong pencerahannya gan :v

**Comment by merkremont** [comment]
I can't understand your language, please speak English in this github ok
