### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by winbotscript** [merkremont/LineVodka#4]
Thank you for writing this script and I can login but I want to ask some things

I use centos 6.9 Final and install pyton 2.7 but when I close Putty SSH why does not it work well all its command ???

For Kick command, NK and gname why not work ???
Please help: v

**Comment by merkremont** [comment]
1. If you turn off the modem/internet wifi, can you surfing websites? If no, you can think again.
2. You should learn python basics and guide of GitHub beginner users from Internet

That's all my answer of your questions. Thank you
