### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Noxturnix** [merkremont/LineVodka#6]
First, I want to say that my English is always bad.

I ran the script and use account A to login. The group name "test" have 2 members in the group (A and B). I send a message from B to the "test" group and the script do nothing. But when I send a message from A to the "test" group, the script return this:

    # python vodkabot.py
    Login qrcode to your smartphone in 2 minutes
    line://au/q/Piq0GEhcBTOJEM21kxn5evLGvkmsWNN2
    VodkaBot
    
    authToken : [[censored]]
    
    certificate :
    
    name : [[censored]]
    None
    argument of type 'NoneType' is not iterable
    
    
    SEND_MESSAGE

**Comment by Gabrieeeltd** [comment]
That's normal, try to type " gift " and send 

gift... no capitalised letter.

**Comment by Noxturnix** [comment]
Still return the same.

**Comment by thomasaryanto** [comment]
yes i have same error like this.

**Comment by merkremont** [comment]
Turn off your 'Letter Sealing' from your LINE Settings, then repeat again

**Comment by thomasaryanto** [comment]
@merkremont thank you, now its working

**Comment by Noxturnix** [comment]
Thank you. The script work perfectly.
